# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07a0cd8f1c19461450d180883a9962b00a7d32ebf4245e6e144f040f467d98f0373d18b08366a1e3d89863c64c72f3f2c6503939b96521b8d242579f00a605e0

test:
  secret_key_base: c178f31a59f2621910f5255ff04482af4a2d4ae630ae1e7ee452bc0071297091045eff74ce79e1af94523a76beee35170067dfca690ab1ae193a7e7660c6b7e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
